### PR TITLE
upload files

### PR DESCRIPTION
**Pull request by ZhenruWang**

### CODE REVIEW

**Comment by cridonoso** [comment]
**Problem 0:** _(total score: 10/10)_ 
Working in branch HW6-dev
HW5 was merged
PR was generated


**Problem 2:** _(total score: 30/30)_ 
good job!

**Directory tree**: _(course policy)_ 
[HW2,HW2,HW3,HW3]-final/dev folder not found


Regards

**Comment by lindseysbrown** [comment]
3B: 10/10
Good job!

**Comment by cj-xin** [comment]
### Problem 1

Good job!

**Comment by adityakaran** [comment]
**Problem 3a**
Good job!

**Pull request merged**
